# options for analysis running
run:
  skip-dirs:
    - system_test
    - mockdata
  # default concurrency is a available CPU number
  concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 10m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # use vendor folder instead of mod cache
  modules-download-mode: vendor


# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle, default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true


# all available settings of specific linters
linters-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 20
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 200

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - gocyclo
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - golint
    - interfacer
    - unconvert
    - goconst
    - gocyclo
    - staticcheck
    - unused
    - gosimple
    - dupl
    - gofmt
    - gosec
    #- lll
    - megacheck
  fast: false


issues:
  # Independently from option `exclude` we use default exclude patterns,
  # it can be disabled by this option. To list all
  # excluded by default patterns execute `golangci-lint run --help`.
  # Default value for this option is true.
  exclude-use-default: false
  exclude:
    - "should have comment or be unexported"
    - "comment on exported"
    - "Error return value of `.*` is not checked"
    - "Errors unhandled"
    - ".* could eliminate the following type assertions"
